# Generated by Django 5.1.2 on 2024-10-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtiLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_source', models.GenericIPAddressField(verbose_name='IP Источника')),
                ('attack_date', models.DateTimeField(verbose_name='Дата появления атаки')),
                ('cve', models.CharField(blank=True, max_length=50, null=True, verbose_name='CVE')),
                ('signature', models.CharField(max_length=100, verbose_name='Сигнатура')),
                ('description', models.TextField(verbose_name='Описание атаки')),
                ('country_source', models.CharField(max_length=50, verbose_name='Страна источник')),
                ('owasp_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='OWASP категория')),
                ('response_measures', models.TextField(verbose_name='Меры реагирования')),
            ],
            options={
                'verbose_name': 'CTI запись',
                'verbose_name_plural': 'CTI записи',
            },
        ),
    ]
