# Generated by Django 5.1.2 on 2024-11-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTI_APP', '0003_remove_ctilog_owasp_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctilog',
            name='attack_date',
            field=models.DateField(verbose_name='Дата появления атаки'),
        ),
    ]
