# Generated by Django 5.1.2 on 2024-11-06 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTI_APP', '0004_alter_ctilog_attack_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctilog',
            name='attack_date',
            field=models.IntegerField(help_text='Введите год, когда была обнаружена атака', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Год появления атаки'),
        ),
    ]
