# Generated by Django 5.1.2 on 2024-11-15 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTI_APP', '0005_alter_ctilog_attack_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_source', models.GenericIPAddressField(verbose_name='IP Источника')),
                ('attack_date', models.IntegerField(help_text='Введите год, когда была обнаружена атака', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Год появления атаки')),
                ('country_source', models.CharField(max_length=50, verbose_name='Страна источник')),
            ],
            options={
                'verbose_name': 'Black List IP',
                'verbose_name_plural': 'Black List IP',
            },
        ),
        migrations.RemoveField(
            model_name='ctilog',
            name='attack_date',
        ),
        migrations.RemoveField(
            model_name='ctilog',
            name='country_source',
        ),
        migrations.RemoveField(
            model_name='ctilog',
            name='ip_source',
        ),
    ]
